### ISSUE TITLE
请问论文中的指标对应的配置文件是什么

### ISSUE THREAD

**Issue by TalkUHulk** [wangxiyang2022/MMF-JDT#2]
使用repo默认的kitti.yaml测试，得到的结果如下：
<img width="590" alt="iShot_2024-11-27_10 22 16" src="https://github.com/user-attachments/assets/1bbba70e-c2c6-4aae-a013-542027b7a418">

<img width="764" alt="iShot_2024-11-27_10 18 08" src="https://github.com/user-attachments/assets/60fe0b22-d60e-4760-82a4-3e6ddbd661ae">

请问paper中的指标如何复现：
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/4eefac9f-bd15-4dd9-9232-cb8c4de4b70e">

**Comment by shahriar0651** [comment]
@TalkUHulk could you please share how did you solve the issue? When I change the `"training"` to `"testing"`, I get the following error.

```python
Traceback (most recent call last):
  File "kitti_main.py", line 172, in <module>
    results = eval_kitti()
  File "/home/hasan/workspace/MMF-JDT/evaluation/KITTI/evaluation_HOTA/scripts/run_kitti.py", line 80, in eval_kitti
    dataset_list = [trackeval.datasets.Kitti2DBox(dataset_config)]
  File "/home/hasan/workspace/MMF-JDT/evaluation/KITTI/evaluation_HOTA/trackeval/datasets/kitti_2d_box.py", line 87, in __init__
    raise TrackEvalException('GT file not found: ' + os.path.basename(curr_file))
trackeval.utils.TrackEvalException: GT file not found: 0021.txt
```

I also wonder if your `testing` dataset portion contains `label_02` folder as mentioned in the README. As far as I know only the `training` portion comes with the `label_02`.

```
# Kitti Tracking Dataset 

├── data
│   ├── kitti
│   │   │── tracking
│   │   │   │──testing
|   │   │   │   ├──calib
|   │   │   │   |    ├──0000.txt
|   │   │   │   |    ├──....txt
|   │   │   │   |    └──0028.txt
|   │   │   │   ├──image_02
|   │   │   │   |    ├──0000
|   │   │   │   |    ├──....
|   │   │   │   |    └──0028
|   │   │   │   ├──oxts
|   │   │   │   |    ├──0000.txt
|   │   │   │   |    ├──....
|   │   │   │   |    └──0028.txt
|   │   │   │   ├──label_02
|   │   │   │   |    ├──0000.txt
|   │   │   │   |    ├──....txt
|   │   │   │   |    └──0028.txt
|   │   │   │   ├──velodyne
|   │   │   │   |    ├──0000
|   │   │   │   |    ├──....
|   │   │   │   |    └──0028  
```

Thanks a lot!

**Comment by TalkUHulk** [comment]
> [@TalkUHulk](https://github.com/TalkUHulk) could you please share how did you solve the issue? When I change the `"training"` to `"testing"`, I get the following error.
> 
> Traceback (most recent call last):
>   File "kitti_main.py", line 172, in <module>
>     results = eval_kitti()
>   File "/home/hasan/workspace/MMF-JDT/evaluation/KITTI/evaluation_HOTA/scripts/run_kitti.py", line 80, in eval_kitti
>     dataset_list = [trackeval.datasets.Kitti2DBox(dataset_config)]
>   File "/home/hasan/workspace/MMF-JDT/evaluation/KITTI/evaluation_HOTA/trackeval/datasets/kitti_2d_box.py", line 87, in __init__
>     raise TrackEvalException('GT file not found: ' + os.path.basename(curr_file))
> trackeval.utils.TrackEvalException: GT file not found: 0021.txt
> I also wonder if your `testing` dataset portion contains `label_02` folder as mentioned in the README. As far as I know only the `training` portion comes with the `label_02`.
> 
> ```
> # Kitti Tracking Dataset 
> 
> ├── data
> │   ├── kitti
> │   │   │── tracking
> │   │   │   │──testing
> |   │   │   │   ├──calib
> |   │   │   │   |    ├──0000.txt
> |   │   │   │   |    ├──....txt
> |   │   │   │   |    └──0028.txt
> |   │   │   │   ├──image_02
> |   │   │   │   |    ├──0000
> |   │   │   │   |    ├──....
> |   │   │   │   |    └──0028
> |   │   │   │   ├──oxts
> |   │   │   │   |    ├──0000.txt
> |   │   │   │   |    ├──....
> |   │   │   │   |    └──0028.txt
> |   │   │   │   ├──label_02
> |   │   │   │   |    ├──0000.txt
> |   │   │   │   |    ├──....txt
> |   │   │   │   |    └──0028.txt
> |   │   │   │   ├──velodyne
> |   │   │   │   |    ├──0000
> |   │   │   │   |    ├──....
> |   │   │   │   |    └──0028  
> ```
> 
> Thanks a lot!
In kitti.yaml, tracking_seqs: [0,2,5,6,8,9,12,14,16,18,19]. 

You can only get the txt results when u change the `"training"` to `"testing. And you can submit txt to [kitti](https://www.cvlibs.net/datasets/kitti/user_submit.php) to get the final results.
